## 텐서플로를 이용한 선형회귀

텐서플로 연산(operation)(은 여러 개의 입력을 받아 출력을 만들 수 있다.<br/>

입력과 출력은 tensor라는 다차원 배열이다.<br/>
이는 numpy 배열과 비슷하게 데이터 타입과 크기를 가진다.

In [26]:
import numpy as np
from sklearn.datasets import fetch_california_housing
import tensorflow as tf

In [27]:
# 데이터 셋을 추출하고 
# 모든 훈련 샘플에 편향에 대한 입력 특성(x0 = 1)을 추가
housing = fetch_california_housing()
m, n = housing.data.shape
print(m, n)
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]   # (m, 1)행렬을 만든뒤 housing데이터의 값을 채워넣음.
housing_data_plus_bias

20640 8


array([[   1.        ,    8.3252    ,   41.        , ...,    2.55555556,
          37.88      , -122.23      ],
       [   1.        ,    8.3014    ,   21.        , ...,    2.10984183,
          37.86      , -122.22      ],
       [   1.        ,    7.2574    ,   52.        , ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.        ,    1.7       ,   17.        , ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.        ,    1.8672    ,   18.        , ...,    2.12320917,
          39.43      , -121.32      ],
       [   1.        ,    2.3886    ,   16.        , ...,    2.61698113,
          39.37      , -121.24      ]])

In [32]:

print(X)
print(y)
print(XT)

Tensor("X_1:0", shape=(20640, 9), dtype=float32)
Tensor("y_1:0", shape=(185760, 1), dtype=float32)
Tensor("transpose_1:0", shape=(9, 20640), dtype=float32)


In [43]:
housing.target.shape

(20640,)

tf.tranpose : 전치
tf.matmul : 내적
tf.matrix_inverse : 역행렬을 계산

In [52]:
X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name='X')                # (20640, 9)
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name='y')         # (20640 , 1)
XT = tf.transpose(X)                                                               # (9 20640)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

In [50]:
with tf.Session() as sess:
    theta_value = theta.eval()
    print(theta_value)

[[-3.7078091e+01]
 [ 4.3625212e-01]
 [ 9.4108758e-03]
 [-1.0677672e-01]
 [ 6.4300227e-01]
 [-4.0595369e-06]
 [-3.7829359e-03]
 [-4.2281592e-01]
 [-4.3611628e-01]]


In [15]:
N = 3

A = np.eye(N)
print('A = ', A)
print()

# 행렬에 열추가 방법
B = np.c_[A, A[2]]
print('B = ', B)
print()

# 행렬에 행추가 방법
C = np.r_[A, [A[2]]]
print('C = ', C)

A =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

B =  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]]

C =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [20]:
# 행렬을 행과 열로 변환 방법

t = np.array([1,2,3]) 
print(t)
print()

tt = np.c_[t]
print(tt)

[1 2 3]

[[1]
 [2]
 [3]]
